version: "3.4"
services:
  valhalla-api:
    container_name: "valhalla-api"
    image: valhalla-api:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - valhala-lan
    environment:
      - DB_TYPE=mysql
      - DB_CONNEC_STRING=root:root@(mariadb:3306)/valhaladb?charset=utf8&parseTime=True&loc=Local

  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./volumes/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: valhaladb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - valhala-lan

networks:
  valhala-lan:
