version: "3.4"
services:
  valhalla-api:
    container_name: "valhalla-api"
    image: valhalla-api:latest
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - valhala-lan

  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /tmp/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - valhala-lan

networks:
  valhala-lan:
