name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ["self-hosted", "desenv"]
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        ~/bin/docker rmi valhalla-api --force
        ~/bin/docker build -t valhalla-api .

    - name: Emit repository_dispatch
      uses: mvasigh/dispatch-action@main
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repo: des-valhalla
        owner: cubcoffee
        event_type: sample_push